CREATE TABLE JOINST1 (
col1 Int
);
CREATE TABLE JOINST2 (
col1 Int
);

INSERT INTO JOINST1 VALUES (1);
INSERT INTO JOINST1 VALUES (2);
INSERT INTO JOINST1 VALUES (2);
INSERT INTO JOINST1 VALUES (3);


INSERT INTO JOINST2 VALUES (1);
INSERT INTO JOINST2 VALUES (2);

SELECT * FROM JOINST1;
SELECT * FROM JOINST2;

SELECT JOINST1.col1, JOINST2.col1 
FROM  JOINST1
LEFT OUTER JOIN JOINST2 ON JOINST2.col1 =  JOINST1.col1;

SELECT JOINST1.col1, JOINST2.col1 
FROM  JOINST2 
LEFT OUTER JOIN JOINST1 ON JOINST2.col1 =  JOINST1.col1;

SELECT SUBSTR("123456789",INSTR("abcabcabc","b"),4) FROM DUAL;